apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/cluster-1/kubeseal/sealed-secrets
    repoURL: https://github.com/cdalar/argocd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
