---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgB4BETgjQN9I8WFURfgixA4Dr3z6TLCBtoTJBsx6yL0O4dsER+Z0KyMB7jAyur50VXU/mD8aErlL8/BSS6D4NK5EEIWMC29N1e+uIZd/oSxl4rVPsipJs4u/HLFl2CfEDTtojoFQJc/0UCT8CpYSVHejpjtoQoP37f+Ef70ipmBcmyGtrKMzAjQ3K/rTPLwj4EKh430iYC01EcIXi3nrygJosq7H0BFVBXEGf0Ju9yNx139sm8s5TGE6xuJALb5nujGaELSluO7Erpvdv9vMQDxsClbjnVl89LBXrJE2JWLoztr6EEwc2BzJOkKm/8AVeQmE7I5QMj4cYfH0WOT4ZYHznm5uOtBXnAyAhq02sZRkMePAH9BhEDsuGsaFfHoi5uRBQzSFJvBxr0ED2kyyY2A03khISNrzT9ZPmDm20fqV6SPCM95OWIGYPUor/B5SJRWB1OOlRZBROGsU+dBF3nfZ5FmL08Gc8luTA4HU9+2iHdMUHRsDkogCoBdml8M7NxwWD5/sBcL7RjJA9TKb4TcQdlHtyyv211tofKkfI38GUu7f7Jv4oQJmhLyNcjnkuCIxYvLEA7OcZlfV/YaIb8AncG+lIi+BR4NkIZ9+wnGOuWFnJUzurpx4lcON+CNkSReyS742d+NKNBpj5AGDc+eD6/iC9JkiVlXwij6vRDgEcxfcajAsku1ZiTFdbk4Tx8Da+Nmq9RI/HDnxfaPhVhQlnny9MN9X6ZctM4rnLa7nPxARsOoSMDK5OflB5Egtng2/YbGn8mvRenU16bchEyK
  template:
    metadata:
      creationTimestamp: null
      name: hcloud
      namespace: kube-system
